# Dimensionality Reduction
### *Using PCA*

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

from matplotlib import pyplot as plt

In [2]:
train = pd.read_csv('data/train.csv')
test = pd.read_csv('data/test.csv')

In [5]:
# Doing a pairplot again
# sns.pairplot(train, hue='y', corner=True);

In [6]:
xtrain, ytrain = train[['x1', 'x2', 'x3']].to_numpy(), train['y'].to_numpy()
xtest, ytest = test[['x1', 'x2', 'x3']].to_numpy(), test['y'].to_numpy()

In [10]:
# Find principle components by finding eigenvalues and vectors
sample_covariance = np.cov(xtrain.T)
eigenvals, eigenvectors = np.linalg.eigh(sample_covariance)
# Printing the result; we see that the top eigenvalue is 9.52, and a corresponding eigenvector!
print(eigenvals)
print(eigenvectors)

[1.0281754  3.75685095 9.51943039]
[[ 0.32817347  0.33721881 -0.882375  ]
 [ 0.31668806 -0.91932561 -0.23355747]
 [-0.88994991 -0.20279026 -0.40849145]]


In [12]:
# We'll order eigenvectors by descending eigenvalues!
order = np.argsort(eigenvals)[::-1]
eigenvals = eigenvals[order]
eigenvectors = eigenvectors[:, order]
# Printing the correct order - eigenvals are actually the variance!
print(eigenvals)
print(eigenvectors)

[9.51943039 3.75685095 1.0281754 ]
[[-0.882375    0.33721881  0.32817347]
 [-0.23355747 -0.91932561  0.31668806]
 [-0.40849145 -0.20279026 -0.88994991]]


In [15]:
pca_xtrain = xtrain @ eigenvectors
pca_xtest = xtest @ eigenvectors

In [22]:
pca_train = pd.DataFrame(np.c_[pca_xtrain, ytrain], columns=['p1','p2','p3','y'])
# Doing a pairplot again againL
# sns.pairplot(pca_train, hue='y', corner=True);