In [39]:
import numpy as np
import networkx as nx
import random

# Chapther 5

## Exercise 5.1

In [20]:
G = nx.read_edgelist('Data/ex_5_1.txt')

In [21]:
Adj_mx = nx.to_numpy_matrix(G)
Adj_mx

matrix([[0., 1., 1., ..., 0., 0., 0.],
        [1., 0., 1., ..., 0., 0., 0.],
        [1., 1., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
Adj_mx_stoc = Adj_mx / Adj_mx.sum(axis=1)
Adj_mx_stoc

matrix([[0.        , 0.03333333, 0.03333333, ..., 0.        , 0.        ,
         0.        ],
        [0.04347826, 0.        , 0.04347826, ..., 0.        , 0.        ,
         0.        ],
        [0.02631579, 0.02631579, 0.        , ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]])

In [10]:
lapl_mx = nx.laplacian_matrix(G);
lapl_mx.todense()

matrix([[30, -1, -1, ...,  0,  0,  0],
        [-1, 23, -1, ...,  0,  0,  0],
        [-1, -1, 38, ...,  0,  0,  0],
        ...,
        [ 0,  0,  0, ...,  1,  0,  0],
        [ 0,  0,  0, ...,  0,  1,  0],
        [ 0,  0,  0, ...,  0,  0,  1]], dtype=int32)

## Exercise 5.2

In [23]:
G2 = nx.read_edgelist("Data/ex_5_2.txt", data = [("weight", float),])

In [24]:
nodes = nx.algorithms.bipartite.basic.sets(G2)

In [32]:
adjmat = nx.algorithms.bipartite.matrix.biadjacency_matrix(G2, nodes[0]);

C:\Users\jonas\AppData\Local\Temp\ipykernel_1108\68375347.py:1: FutureWarning: biadjacency_matrix will return a scipy.sparse array instead of a matrix in NetworkX 3.0
  adjmat = nx.algorithms.bipartite.matrix.biadjacency_matrix(G2, nodes[0]);


In [33]:
# Project along axis of length 248 (asked in exercise formulation)
## Then it becomes a matrix representation of connection between the 248 nodes through 1 link 
## (i.e. paths of length 2 through the other set of the bipartite!)
if adjmat.shape[0] == 248:
   adjmat_proj = adjmat.dot(adjmat.T)
else:
   adjmat_proj = adjmat.T.dot(adjmat)

In [34]:
# Make stocastic
adjmat_proj_stoc = adjmat_proj / adjmat_proj.sum(axis = 1)
print(adjmat_proj_stoc)

[[1.04934942e-02 2.25140841e-03 0.00000000e+00 ... 6.25391226e-03
  2.75172139e-04 0.00000000e+00]
 [3.19952699e-03 4.11167285e-02 0.00000000e+00 ... 2.80660263e-03
  1.23490516e-04 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.99874902e-01 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 ...
 [6.84282401e-03 2.16089179e-03 0.00000000e+00 ... 4.44052939e-02
  2.64108997e-04 0.00000000e+00]
 [3.35026992e-03 1.05797997e-03 0.00000000e+00 ... 2.93883326e-03
  2.67295969e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 4.93144388e-01]]


### Exercise 5.3

Continuation of 5.2

In [35]:
# Eigenvalues and Eigenvectors. Right eigenvectors first.
values, vectors_r = np.linalg.eig(adjmat_proj_stoc)

In [36]:
# We need to sort the eigenvalues and eigenvectors, since numpy returns them in random order
sorted_index = values.argsort()[::-1]
values = np.real(values[sorted_index])
vectors_r = np.real(vectors_r[:,sorted_index])

In [37]:
# Now left eigenvectors.
values, vectors_l = np.linalg.eig(adjmat_proj_stoc.T)
sorted_index = values.argsort()[::-1]
values = np.real(values[sorted_index])
vectors_l = np.real(vectors_l[:,sorted_index])

# Chapther 7

## Exercise 7.1

In [38]:
G3 = nx.read_edgelist('Data/ex_7_1.txt')

In [54]:
# Arbitrary choice of starting node
start = random.choice(list(G3.nodes))

In [55]:
# Arbitrary choice of length
length = random.choice(range(20))

In [56]:
# Walk!
walk = [start,]
current = start
for _ in range(length):
    current = random.choice(list(G3.neighbors(current)))
    walk.append(current)

In [57]:
print(walk)

['20505', '2698', '20724', '2698', '32268', '2698', '19498', '2698', '40']
